server:
  port: 9000

spring:
#  application:
#    name: SAVE

  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8??
  sql:
    init:
      platform: mysql